# Generated by Django 2.2.10 on 2020-02-08 04:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Payment Amount')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.Contract', verbose_name='Related Contract')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date'],
            },
        ),
    ]
