# Generated by Django 2.2.10 on 2020-02-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='contract',
            new_name='contract_id',
        ),
    ]
