# Generated by Django 5.0.1 on 2024-02-05 22:27

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loans",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor do Empréstimo",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Taxa de Juros Mensal",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        max_length=15,
                        verbose_name="Endereço IPv4 do Solicitante",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data de Solicitação do Empréstimo",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        max_length=128, verbose_name="Instituição Financeira"
                    ),
                ),
                (
                    "installments",
                    models.IntegerField(verbose_name="Quantidade de Parcelas"),
                ),
                (
                    "cet_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Custo Efetivo Total",
                    ),
                ),
                (
                    "iof_interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Imposto sobre operações financeiras",
                    ),
                ),
                (
                    "insurance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Porcentagem do Seguro Prestamista",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante do Empréstimo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empréstimo",
                "verbose_name_plural": "Empréstimos",
            },
        ),
    ]
