# Generated by Django 2.2.3 on 2020-02-07 12:11

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.TextField(help_text='Contract Bank')),
                ('amount', models.FloatField(help_text='Contract Price', validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('interest_rate', models.FloatField(help_text='Interest Rate', validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1)])),
                ('submission_date', models.DateField(help_text='Submission Date')),
                ('ip_address', models.GenericIPAddressField(help_text='Ip Adress of submission')),
            ],
            options={
                'ordering': ['client_id'],
            },
        ),
    ]
