# Generated by Django 2.2.10 on 2020-02-08 04:53

import contracts.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Amount owed to the Bank')),
                ('interest_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Monthly interest Rate')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP of the contract Submitter')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Submission Date')),
                ('bank', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[contracts.models.validate_json], verbose_name='Bank Information')),
                ('customer_metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, validators=[contracts.models.validate_json], verbose_name='Customer Metadata')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Owner')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-submission_date'],
            },
        ),
    ]
